# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaOftalmologia', '0019_auto_20160321_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eps',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='especialidad_medica',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='observaciones',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='modopago',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='modopago',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(max_length=50, blank=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='primer_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundo_apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(max_length=10, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultados',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tipo_empleado',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tipo_empleado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipo_examen',
            name='nombre',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tipo_tratamiento',
            name='descripcion',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='observaciones',
            field=models.TextField(max_length=140),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
