# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaOftalmologia', '0030_auto_20160419_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
