# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreaOftalmologia', '0034_auto_20160525_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Lunes a Sabado', 'Lunes a Sabado'), ('Lunes a Viernes', 'Lunes a Viernes'), ('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'viernes'), ('Sabado', 'Sabado')], max_length=20),
        ),
    ]
